name: cnattendance
description: An attendance application to manage in a organization to check in and check out with multiple functions to manupulate inside a office to record the basic functionality
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  full_screen_image: ^2.0.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  http: ^1.1.0
  dio: ^5.1.2
  html: ^0.15.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.0.6
  flutter_easyloading: ^3.0.5
  device_info_plus: ^9.0.3
  expandable: ^5.0.1
  flutter_expanded_tile: ^0.3.7
  flutter_web_browser: ^0.17.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  toggle_switch: ^2.0.1
  dropdown_button3: ^3.0.0
  flutter_html: ^3.0.0-alpha.3
  url_launcher: ^6.1.5
  local_auth: ^2.1.2
  open_file: ^3.3.2
  table_calendar: ^3.0.6
  intl: ^0.18.1
  image_picker: ^1.0.4
  network_info_plus: ^4.0.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  overlay_support: ^2.0.1
  flutter_ringtone_player: ^3.2.0
  fl_chart: ^0.64.0
  overlay_loading_progress: ^1.0.0
  slide_digital_clock: ^1.0.2
  get: ^4.6.5
  readmore: ^2.1.0
  image_stack: ^2.1.1
  in_app_notification: ^1.1.2
  #flutter_file_downloader: ^1.1.0+1
  gallery_image_viewer: ^1.2.0
  flutter_typeahead: ^4.3.7
  flutter_textfield_autocomplete: ^1.0.2

  fluttertoast: ^8.2.1
  flutter_mentions: ^2.0.1
  awesome_notifications: any
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_screenutil: ^5.9.0
  flutter_zoom_drawer: ^3.1.1
  flip_card: ^0.7.0
  lottie: ^2.7.0
  expandable_text: ^2.3.0

  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3

  #google map
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.0.1
  permission_handler: ^10.0.1

  #file
  file_picker: ^6.1.1
  images_picker: ^1.2.11
  path_provider: ^2.1.2

  dartz: any

  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2

  printing: ^5.11.1
  screenshot: ^2.1.0

  syncfusion_flutter_gauges: ^24.2.6


  #flutter_inappwebview: ^6.0.0
  device_preview: ^1.1.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/appLogoWithOutBackground.png"
  remove_alpha_ios: true
  min_sdk_android: 21

change_app_package_name:
  flutter_test:
    sdk: flutter
  rename: ^3.0.1



flutter:
  uses-material-design: true
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/UrbanistGX.ttf




  assets:
    - assets/icons/
    - assets/images/
    - assets/sound/
    - assets/ca/
    - assets/icons/svg/
    - assets/animation/


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700